Use seed-services-client for API requests
Instead of hardcoding URLs in this repo, use the API client.

The test test_create_outbound_data_new_identity fails with this
code change in Python 3 because:

> AttributeError: 'str' object has no attribute 'decode'